// flow-typed signature: 93c7c0bc5a60790dfd95d5e3f9a1982e
// flow-typed version: <<STUB>>/fast-async_v^6.1.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-async/plugin' {
  declare module.exports: any;
}

declare module 'fast-async/tests/test-input' {
  declare module.exports: any;
}

declare module 'fast-async/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-async/plugin.js' {
  declare module.exports: $Exports<'fast-async/plugin'>;
}
declare module 'fast-async/tests/test-input.js' {
  declare module.exports: $Exports<'fast-async/tests/test-input'>;
}
declare module 'fast-async/tests/test.js' {
  declare module.exports: $Exports<'fast-async/tests/test'>;
}
